package id.calocallo.sicape.model

import id.calocallo.sicape.network.request.*

data class AllPersonelModel(
    var personel: AddPersonelReq,
    var signalement: SignalementModel,
    var foto: FotoReq,
    var relasi: ArrayList<RelasiReq>,
    var pernah_dihukum: ArrayList<HukumanReq>,
    var catatan_personel:CatatanPersReq,
    var riwayat_pendidikan_umum: ArrayList<AddPendidikanModel>,
    var riwayat_pendidikan_kedinasan: ArrayList<AddPendidikanModel>,
    var riwayat_pendidikan_lain_lain: ArrayList<AddPendidikanModel>,
    var riwayat_pekerjaan: ArrayList<AddSinglePekerjaanReq>,
    var pekerjaan_diluar_dinas: ArrayList<PekerjaanODinasReq>,
    var riwayat_alamat: ArrayList<AlamatReq>,
    var riwayat_organisasi: ArrayList<OrganisasiReq>,
    var riwayat_penghargaan: ArrayList<PenghargaanReq>,
    var riwayat_perjuangan: ArrayList<PerjuanganCitaReq>,
    var pasangan: PasanganReq,
    var ayah_kandung: AyahReq,
    var ayah_tiri: AyahTiriReq,
    var ibu_kandung: IbuReq,
    var ibu_tiri: IbuTiriReq,
    var mertua_laki: MertuaLakiReq,
    var mertua_perempuan: MertuaPerempuanReq,
    var anak: ArrayList<AnakReq>,
    var saudara: ArrayList<SaudaraReq>,
    var orang_berjasa: ArrayList<OrangsReq>,
    var orang_disegani: ArrayList<OrangsReq>,
    var tokoh_dikagumi: ArrayList<TokohReq>,
    var sahabat: ArrayList<KawanDekatReq>,
    var media_disenangi: ArrayList<MedInfoReq>,
    var media_sosial: ArrayList<MedsosReq>

) {
    constructor() : this(
        AddPersonelReq(),
        SignalementModel(),
        FotoReq(),
        ArrayList(),
        ArrayList(),
        CatatanPersReq(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        PasanganReq(),
        AyahReq(),
        AyahTiriReq(),
        IbuReq(),
        IbuTiriReq(),
        MertuaLakiReq(),
        MertuaPerempuanReq(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList(),
        ArrayList()
    )
}