package id.calocallo.sicape.model

import android.os.Parcel
import android.os.Parcelable
import id.calocallo.sicape.network.request.FotoReq
import id.calocallo.sicape.network.response.*
import kotlinx.android.parcel.Parcelize

@Parcelize
data class AllPersonelModel(
    var id: Int?,
    var nama: String?,
    var nama_alias: String?,
    var jenis_kelamin: String?,
    var tempat_lahir: String?,
    var tanggal_lahir: String?,
    var ras: String?,
    var jabatan: String?,
    var pangkat: String?,
    var nrp: String?,
    var satuan_kerja: SatKerResp?,
    var alamat_rumah: String?,
    var no_telp_rumah: String?,
    var kewarganegaraan: String?,
    var cara_peroleh_kewarganegaraan: String?,
    var agama_sekarang: String?,
    var agama_sebelumnya: String?,
    var aliran_kepercayaan: String?,
    var status_perkawinan: Int?,
    var tempat_perkawinan: String?,
    var tanggal_perkawinan: String?,
    var perkawinan_keberapa: Int?,
    var jumlah_anak: Int?,
    var alamat_sesuai_ktp: String?,
    var no_telp: String?,
    var no_ktp: String?,
    var hobi: String?,
    var kebiasaan: String?,
    var bahasa: String?,
    var is_user: Int?,
    var signalement: SignalementModel?,
    var foto: FotoReq?,
    var pasangan: ArrayList<PasanganMinResp?>,
    var keluarga: ArrayList<KeluargaMinResp?>,
    var anak: ArrayList<AnakMinResp>?,
    var riwayat_pendidikan: ArrayList<PendidikanMinResp>?,
    var riwayat_pekerjaan: ArrayList<PekerjaanMinResp>?,
    var riwayat_alamat: ArrayList<AlamatMinResp>?,
    var riwayat_organisasi: ArrayList<OrganisasiMinResp>?,
    var riwayat_penghargaan: ArrayList<PenghargaanMinResp>?,
    var riwayat_perjuangan: ArrayList<PerjuanganMinResp>?,
    var media_disenangi: ArrayList<MediaInfoMinResp>?,
    var media_sosial: ArrayList<MedSosMinResp>?,
    var orang_berjasa: ArrayList<OrangsMinResp>?,
    var orang_disegani:  ArrayList<OrangsMinResp>?,
    var pekerjaan_diluar_dinas: ArrayList<PekerjaanLuarDinasMinResp>?,
    var pernah_dihukum: ArrayList<PernahHukumMinResp>?,
    var relasi: ArrayList<RelasiMinResp>?,
    var sahabat: ArrayList<SahabatMinResp>?,
    var saudara: ArrayList<SaudaraMinResp>?,
    var tokoh_dikagumi: ArrayList<TokohMinResp>?,
    var user_creator: UserCreatorResp?,
    var user_updater: UserCreatorResp?,
    val hak_akses: String?,
    val is_aktif: String?,
    var created_at: String?,
    var updated_at: String?
) : Parcelable