package id.calocallo.sicape.model

data class MertuaPerempuanModel (
    val nama: String?,
    val alias: String?,
    val tempat_lhr: String?,
    val tgl_lhr: String?,
    val suku: String?,
    val kwg: String?,
    val how_to_kwg: String?,
    val agama_skrg: String?,
    val agama_sblm: String?,
    val aliran_dianut: String?,
    val aliran_prnh_dianut: String?,
    val almt_sblm_kwin: String?,
    val almt_skrg: String?,
    val no_telp: String?,
    val last_pend: String?,
    val pernikahan_brp: String?,
    val pekerjaan: String?,
    val almt_kantor: String?,
    val no_telp_kantor: String?,
    val pekerjaan_sblm: String?,
    val kedudukan_org_diikuti: String?,
    val thn_org_diikuti: String?,
    val alasan_org_diikuti: String?,
    val almt_org_diikuti: String?,
    val kedudukan_org_diikuti_lain: String?,
    val thn_org_diikuti_lain: String?,
    val alasan_org_diikuti_lain: String?,
    val almt_org_diikuti_lain: String?,

    val stts_hidup: String?,
    val how_hidup: String?,
    val dmna: String?,
    val penyebab: String
)